// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBWXOxzO95hqw-eIhRuK8YXiAMasG4ONs',
    appId: '1:546206935493:web:e55a21d2d0c3c9a02203ac',
    messagingSenderId: '546206935493',
    projectId: 'social-app-86327',
    authDomain: 'social-app-86327.firebaseapp.com',
    storageBucket: 'social-app-86327.firebasestorage.app',
    measurementId: 'G-RXS1HRGFYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGNGzM7ejupyVy_eQfpkhd3xL1XXtVSxA',
    appId: '1:546206935493:android:077ce441c11d48f42203ac',
    messagingSenderId: '546206935493',
    projectId: 'social-app-86327',
    storageBucket: 'social-app-86327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtBrei-BZiq4uosDPu9yKQ01_OundhVUA',
    appId: '1:546206935493:ios:89f77c0b433b4f8b2203ac',
    messagingSenderId: '546206935493',
    projectId: 'social-app-86327',
    storageBucket: 'social-app-86327.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtBrei-BZiq4uosDPu9yKQ01_OundhVUA',
    appId: '1:546206935493:ios:89f77c0b433b4f8b2203ac',
    messagingSenderId: '546206935493',
    projectId: 'social-app-86327',
    storageBucket: 'social-app-86327.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBWXOxzO95hqw-eIhRuK8YXiAMasG4ONs',
    appId: '1:546206935493:web:6dc2d3c84334bda02203ac',
    messagingSenderId: '546206935493',
    projectId: 'social-app-86327',
    authDomain: 'social-app-86327.firebaseapp.com',
    storageBucket: 'social-app-86327.firebasestorage.app',
    measurementId: 'G-9PN1D14ZE5',
  );
}
